version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - python
  pep8:
    enabled: true
exclude_patterns:
- "data/"
- "translations/"
- "app/static/"
- "app/templates/"
- "**/*.js"
- "identicon.py"
