version: '2'

services:
  web:
    restart: always
    build: .
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/local
      - PORT=5000
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: python runserver.py

  mongodb:
    restart: always
    image: mongo:3.0
    volumes:
      - ./data/mongodb:/data
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data

