version: '2'

services:
  web:
    build: .
    environment:
        - MONGODB_URI=mongodb://mongodb:27017/local
        - PORT=5000
        - DEBUG=True
        - WERKZEUG_DEBUG_PIN=off
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - .:/app
    command: python runserver.py

  mongodb:
    image: mongo:3.0
    volumes:
      - ./data/mongodb:/data
    ports:
      - "27017:27017"

networks:
  default:

volumes:
  default:
