version: '2'

services:
  web:
    build:
      context: .
      args:
        - http_proxy=http://proxy.priv.atos.fr:3128/
        - https_proxy=http://proxy.priv.atos.fr:3128/
        - no_proxy=localhost,127.0.0.1,kazan.priv.atos.fr,*.priv.atos.fr
    env_file: .env
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://localhost:27017/local
      - DEBUG=True
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:./app

  db:
    image: mongo:3.0
    ports:
      - "27017:27017"

networks:
  default: