version: '2'

services:
  web:
    build:
      context: .
      args:
        - MONGODB_URI=mongodb://localhost:27017/local
    environment:
        - MONGODB_URI=mongodb://localhost:27017/local
        - PORT=5000
        - DEBUG=True
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mongo:3.0
    ports:
      - "27017:27017"

networks:
  default:
